# Screenshot run right-side dock/wharf-ish strip.
@edge right
@anchor right top bottom
@width 64
@margin right 5
@margin top 4
@dock
AudioPlayer|normal/MusicalNote=:
afterstepdoc|large/AfterStep3=:
WharfExtras|normal/Info=:
ToolsFolder|normal/Desktop=:
XEyes=@xeyes
QuitFolder|normal/RedLight=:
asfsm|normal/Harddrive=:
loadmonitor|normal/Monitor1=:
loadinstantmonitor|normal/Monitor1=:
asmon|normal/Monitor1=:
wmtop|normal/Monitor1=:
netmonitor|normal/Ethernet=:
asmail|normal/MailBox2=:
clock=@clock
