# Screenshot run menu config.
@title AfterStep 2.2.12
@no_desktop_entries
Applications|Folder-Gear2=@submenu
Find...|Folder-MagnifyingGlass=@submenu
Desktop Setup|Folder-Desktop2=@submenu
Modules|Folder-Puzzle=@submenu
Run ...|normal/Run=:
Screen Savers|Folder-MoonInMonitor=@submenu
System Settings|Folder-Gear2=@submenu
Windows|Folder-Windows=@submenu
XTerminal|mini-app.xpm=${TERMINAL:-xterm -fa Monospace -fs 12}
Quit|Folder-Stopsign=@submenu
About AfterStep|Folder-Info=@submenu
