# AfterStep Wayland default panel (Wharf-ish).

@edge top
@dock
@height 64
@margin left 1
@margin top 1

Menu|large/AfterStep3=aswlmenu
Terminal|normal/Terminal=${TERMINAL:-foot}
Browser|normal/WWW=${BROWSER:-firefox}
Files|normal/Filecabinet2=${FILE_MANAGER:-pcmanfm}

Prev WS|dots/arrow_small=@workspace_prev
Next WS|dots/lined_arrow=@workspace_next

Close|dots/abi-close=@close

@workspaces 4

