# Screenshot run top dock (Wharf-ish) config.
@edge top
@anchor left top
@margin left 1
@margin top 1
@width 960
@dock
Wharf extras|normal/Info=:
term|normal/Terminal=${TERMINAL:-xterm -fa Monospace -fs 12}
MidnightCommander|normal/MCInMonitorShadow=:
GUIFileManager|normal/Filecabinet2=:
Konqueror|logos/konqueror=:
WebBrowser|normal/WWW=:
Mail|normal/MailBox2=:
ImageEditor|logos/gimp=:
TextEditor|Text.xpm=:
WordProcessor|normal/Document=:
Spreadsheet|normal/Table=:
IRC|normal/IRCTransparent=:
Games|normal/GameController=:
AudioPlayer|normal/MusicalNote=:
mixer|normal/Speaker=:
