# Screenshot run right-side dock/wharf-ish strip.
@edge right
@anchor right bottom
@margin right 5
@margin bottom 5
@dock
afterstepdoc|large/AfterStep3=:
WharfExtras|normal/Info=:
Tools|normal/Desktop=:
XEyes|normal/EyeInMonitorShadow=xeyes
QuitFolder|normal/RedLight=:
asfsm|normal/Harddrive=:
loadmonitor|normal/Monitor1=:
netmonitor|normal/Ethernet=:
asmail|normal/MailBox2=:
Clock=@clock
